version: '2'
services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app/
      - /app/node_modules
      # Change this to point to a folder where you have
      # packages to use checked out
      - ~/Code:/code
    ports:
      - "3000:3000"
